-- Database schema for the community map
-- Run in your Supabase project's SQL editor

-- Extensions
create extension if not exists "uuid-ossp";
create extension if not exists pgcrypto;

create table if not exists public.pins (
  id uuid primary key default gen_random_uuid(),
  lat double precision not null,
  lng double precision not null,
  city text,
  state_province text,
  country text,
  country_code text,
  icon text,
  nickname text,
  age int,
  genders text[] not null default '{}',
  gender_identity text not null default 'unspecified',
  seeking text[] not null default '{}',
  interest_tags text[] not null default '{}',
  note text,
  contact_methods jsonb not null default '{}',
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  approved boolean not null default false,
  submitted_at timestamptz not null default now(),
  expires_at timestamptz,
  never_delete boolean not null default false,
  approved_at timestamptz
);

-- Backfill columns for deployments created before this revision
alter table public.pins add column if not exists country_code text;
alter table public.pins add column if not exists icon text;
alter table public.pins add column if not exists nickname text;
alter table public.pins add column if not exists age int;
alter table public.pins add column if not exists genders text[] not null default '{}';
alter table public.pins add column if not exists contact_methods jsonb not null default '{}';
alter table public.pins add column if not exists expires_at timestamptz;
alter table public.pins add column if not exists never_delete boolean not null default false;
alter table public.pins
  add column if not exists status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected'));
alter table public.pins add column if not exists approved boolean not null default false;

create index if not exists pins_status_idx on public.pins (status);
create index if not exists pins_approved_idx on public.pins (approved);

-- Bubble options for selectable chips on the submission form
create table if not exists public.bubble_options (
  id bigint generated by default as identity primary key,
  field text not null check (field in ('gender_identity', 'seeking', 'interest_tags', 'contact_methods')),
  label text not null,
  status text not null default 'approved' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now()
);

-- Ensure legacy tables get the status column before creating indexes
alter table public.bubble_options
  add column if not exists status text not null default 'approved'
    check (status in ('pending', 'approved', 'rejected'));

create index if not exists bubble_options_field_idx on public.bubble_options (field);
create index if not exists bubble_options_status_idx on public.bubble_options (status);

-- Messages and reports submitted by site visitors
create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  kind text not null check (kind in ('site_feedback', 'pin_report')),
  message text not null,
  contact_info text,
  pin_id uuid references public.pins (id) on delete set null,
  status text not null default 'open' check (status in ('open', 'resolved')),
  created_at timestamptz not null default now()
);

alter table public.messages add column if not exists kind text;
alter table public.messages alter column kind type text;
alter table public.messages
  alter column kind set not null,
  alter column kind set default 'site_feedback';
alter table public.messages
  drop constraint if exists messages_kind_check;
alter table public.messages
  add constraint messages_kind_check check (kind in ('site_feedback', 'pin_report'));
alter table public.messages add column if not exists message text;
alter table public.messages alter column message type text;
alter table public.messages alter column message set not null;
alter table public.messages add column if not exists contact_info text;
alter table public.messages add column if not exists pin_id uuid;
alter table public.messages add column if not exists status text not null default 'open';
alter table public.messages
  drop constraint if exists messages_status_check;
alter table public.messages
  add constraint messages_status_check check (status in ('open', 'resolved'));
alter table public.messages add column if not exists created_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'messages_pin_id_fkey'
  ) then
    alter table public.messages
      add constraint messages_pin_id_fkey foreign key (pin_id)
      references public.pins (id) on delete set null;
  end if;
end $$;

create index if not exists messages_status_idx on public.messages (status);
create index if not exists messages_pin_idx on public.messages (pin_id);
create index if not exists messages_created_idx on public.messages (created_at desc);

-- Enable row level security
alter table public.pins enable row level security;
alter table public.bubble_options enable row level security;
alter table public.messages enable row level security;
