-- Database schema for the community map
-- Run in your Supabase project's SQL editor

-- Extensions
create extension if not exists "uuid-ossp";
create extension if not exists pgcrypto;

create table if not exists public.pins (
  id uuid primary key default gen_random_uuid(),
  lat double precision not null,
  lng double precision not null,
  city text,
  state_province text,
  country text,
  country_code text,
  icon text,
  nickname text,
  age int,
  genders text[] not null default '{}',
  gender_identity text not null default 'unspecified',
  seeking text[] not null default '{}',
  interest_tags text[] not null default '{}',
  note text,
  contact_methods jsonb not null default '{}',
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  approved boolean not null default false,
  submitted_at timestamptz not null default now(),
  expires_at timestamptz,
  approved_at timestamptz
);

-- Backfill columns for deployments created before this revision
alter table public.pins add column if not exists country_code text;
alter table public.pins add column if not exists icon text;
alter table public.pins add column if not exists nickname text;
alter table public.pins add column if not exists age int;
alter table public.pins add column if not exists genders text[] not null default '{}';
alter table public.pins add column if not exists contact_methods jsonb not null default '{}';
alter table public.pins add column if not exists expires_at timestamptz;
alter table public.pins
  add column if not exists status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected'));
alter table public.pins add column if not exists approved boolean not null default false;

create index if not exists pins_status_idx on public.pins (status);
create index if not exists pins_approved_idx on public.pins (approved);

-- Bubble options for selectable chips on the submission form
create table if not exists public.bubble_options (
  id bigint generated by default as identity primary key,
  field text not null check (field in ('gender_identity', 'seeking', 'interest_tags', 'contact_methods')),
  label text not null,
  status text not null default 'approved' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now()
);

create index if not exists bubble_options_field_idx on public.bubble_options (field);
create index if not exists bubble_options_status_idx on public.bubble_options (status);

alter table public.bubble_options
  add column if not exists status text not null default 'approved'
    check (status in ('pending', 'approved', 'rejected'));

-- Enable row level security
alter table public.pins enable row level security;
alter table public.bubble_options enable row level security;
