drop extension if exists "pg_net";


  create table "public"."bubble_options" (
    "id" bigint generated by default as identity not null,
    "field" text not null,
    "label" text not null,
    "created_at" timestamp with time zone not null default now(),
    "status" text not null default 'approved'::text,
    "created_by" uuid default auth.uid()
      );


alter table "public"."bubble_options" enable row level security;


  create table "public"."messages" (
    "id" uuid not null default gen_random_uuid(),
    "kind" text not null default 'site_feedback'::text,
    "message" text not null,
    "contact_info" text,
    "pin_id" uuid,
    "status" text not null default 'open'::text,
    "created_at" timestamp with time zone not null default now(),
    "created_by" uuid default auth.uid()
      );


alter table "public"."messages" enable row level security;


  create table "public"."moderators" (
    "user_id" uuid not null,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."moderators" enable row level security;


  create table "public"."pending_pin_locations" (
    "pin_id" uuid not null,
    "lat" double precision not null,
    "lng" double precision not null,
    "submitted_at" timestamp with time zone default now()
      );


alter table "public"."pending_pin_locations" enable row level security;


  create table "public"."pins" (
    "id" uuid not null default gen_random_uuid(),
    "lat" double precision not null,
    "lng" double precision not null,
    "city" text,
    "state_province" text,
    "country" text,
    "gender_identity" text not null,
    "seeking" text[] not null,
    "interest_tags" text[],
    "note" text,
    "contact_discord" text,
    "contact_reddit" text,
    "contact_instagram" text,
    "status" text default 'pending'::text,
    "approved" boolean default false,
    "submitted_at" timestamp with time zone default now(),
    "approved_at" timestamp with time zone,
    "ip_hash" text,
    "country_code" text,
    "icon" text,
    "nickname" text,
    "age" integer,
    "genders" text[] not null default '{}'::text[],
    "contact_methods" jsonb not null default '{}'::jsonb,
    "expires_at" timestamp with time zone,
    "never_delete" boolean not null default false,
    "created_by" uuid default auth.uid()
      );


alter table "public"."pins" enable row level security;


  create table "public"."turnstile_rate_limits" (
    "key" text not null,
    "window_started" timestamp with time zone not null default now(),
    "request_count" integer not null default 0,
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."turnstile_rate_limits" enable row level security;


  create table "public"."turnstile_sessions" (
    "id" uuid not null,
    "fingerprint" text not null,
    "ip" inet,
    "issued_at" timestamp with time zone not null default now(),
    "expires_at" timestamp with time zone not null
      );


alter table "public"."turnstile_sessions" enable row level security;

CREATE INDEX bubble_options_field_idx ON public.bubble_options USING btree (field);

CREATE UNIQUE INDEX bubble_options_pkey ON public.bubble_options USING btree (id);

CREATE INDEX bubble_options_status_idx ON public.bubble_options USING btree (status);

CREATE INDEX messages_created_idx ON public.messages USING btree (created_at DESC);

CREATE INDEX messages_pin_idx ON public.messages USING btree (pin_id);

CREATE UNIQUE INDEX messages_pkey ON public.messages USING btree (id);

CREATE INDEX messages_status_idx ON public.messages USING btree (status);

CREATE UNIQUE INDEX moderators_pkey ON public.moderators USING btree (user_id);

CREATE UNIQUE INDEX pending_pin_locations_pkey ON public.pending_pin_locations USING btree (pin_id);

CREATE INDEX pins_approved_idx ON public.pins USING btree (approved);

CREATE UNIQUE INDEX pins_pkey ON public.pins USING btree (id);

CREATE INDEX pins_status_idx ON public.pins USING btree (status);

CREATE UNIQUE INDEX turnstile_rate_limits_pkey ON public.turnstile_rate_limits USING btree (key);

CREATE INDEX turnstile_sessions_fingerprint_idx ON public.turnstile_sessions USING btree (fingerprint);

CREATE UNIQUE INDEX turnstile_sessions_pkey ON public.turnstile_sessions USING btree (id);

alter table "public"."bubble_options" add constraint "bubble_options_pkey" PRIMARY KEY using index "bubble_options_pkey";

alter table "public"."messages" add constraint "messages_pkey" PRIMARY KEY using index "messages_pkey";

alter table "public"."moderators" add constraint "moderators_pkey" PRIMARY KEY using index "moderators_pkey";

alter table "public"."pending_pin_locations" add constraint "pending_pin_locations_pkey" PRIMARY KEY using index "pending_pin_locations_pkey";

alter table "public"."pins" add constraint "pins_pkey" PRIMARY KEY using index "pins_pkey";

alter table "public"."turnstile_rate_limits" add constraint "turnstile_rate_limits_pkey" PRIMARY KEY using index "turnstile_rate_limits_pkey";

alter table "public"."turnstile_sessions" add constraint "turnstile_sessions_pkey" PRIMARY KEY using index "turnstile_sessions_pkey";

alter table "public"."bubble_options" add constraint "bubble_options_field_check" CHECK ((field = ANY (ARRAY['gender_identity'::text, 'seeking'::text, 'interest_tags'::text, 'contact_methods'::text]))) not valid;

alter table "public"."bubble_options" validate constraint "bubble_options_field_check";

alter table "public"."bubble_options" add constraint "bubble_options_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text]))) not valid;

alter table "public"."bubble_options" validate constraint "bubble_options_status_check";

alter table "public"."messages" add constraint "messages_kind_check" CHECK ((kind = ANY (ARRAY['site_feedback'::text, 'pin_report'::text]))) not valid;

alter table "public"."messages" validate constraint "messages_kind_check";

alter table "public"."messages" add constraint "messages_pin_id_fkey" FOREIGN KEY (pin_id) REFERENCES public.pins(id) ON DELETE SET NULL not valid;

alter table "public"."messages" validate constraint "messages_pin_id_fkey";

alter table "public"."messages" add constraint "messages_status_check" CHECK ((status = ANY (ARRAY['open'::text, 'resolved'::text]))) not valid;

alter table "public"."messages" validate constraint "messages_status_check";

alter table "public"."moderators" add constraint "moderators_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."moderators" validate constraint "moderators_user_id_fkey";

alter table "public"."pending_pin_locations" add constraint "pending_pin_locations_pin_id_fkey" FOREIGN KEY (pin_id) REFERENCES public.pins(id) ON DELETE CASCADE not valid;

alter table "public"."pending_pin_locations" validate constraint "pending_pin_locations_pin_id_fkey";

alter table "public"."pins" add constraint "pins_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text]))) not valid;

alter table "public"."pins" validate constraint "pins_status_check";

alter table "public"."turnstile_sessions" add constraint "turnstile_sessions_expiry" CHECK ((expires_at > issued_at)) not valid;

alter table "public"."turnstile_sessions" validate constraint "turnstile_sessions_expiry";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.bump_turnstile_limit(p_key text, p_window_seconds integer, p_limit integer)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_record public.turnstile_rate_limits%rowtype;
  v_reset boolean := false;
begin
  select *
    into v_record
    from public.turnstile_rate_limits
   where key = p_key
   for update;

  if not found then
    insert into public.turnstile_rate_limits (key, request_count)
    values (p_key, 1);
    return true;
  end if;

  if v_record.window_started < now() - make_interval(secs => greatest(p_window_seconds, 1)) then
    update public.turnstile_rate_limits
       set window_started = now(),
           request_count = 1,
           updated_at = now()
     where key = p_key;
    return true;
  end if;

  if v_record.request_count >= p_limit then
    return false;
  end if;

  update public.turnstile_rate_limits
     set request_count = v_record.request_count + 1,
         updated_at = now()
   where key = p_key;
  return true;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.debug_turnstile()
 RETURNS json
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  select json_build_object(
    'db_role', current_setting('role', true),      -- this is the role RLS uses
    'current_user', current_user,
    'session_user', session_user,
    'role_claim', current_setting('request.jwt.claim.role', true),
    'turnstile_passed', (auth.jwt()->>'turnstile_passed')::boolean
  );
$function$
;

CREATE OR REPLACE FUNCTION public.is_moderator(uid uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (select 1 from public.moderators m where m.user_id = uid);
$function$
;

CREATE OR REPLACE FUNCTION public.is_request_owner(owner uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE
AS $function$
  select owner is not distinct from auth.uid();
$function$
;

CREATE OR REPLACE FUNCTION public.record_turnstile_session(p_session_id uuid, p_fingerprint text, p_ip inet, p_ttl_seconds integer)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.turnstile_sessions (id, fingerprint, ip, expires_at)
  values (
    p_session_id,
    p_fingerprint,
    p_ip,
    now() + make_interval(secs => greatest(p_ttl_seconds, 60))
  )
  on conflict (id) do update
    set fingerprint = excluded.fingerprint,
        ip = excluded.ip,
        expires_at = excluded.expires_at,
        issued_at = now();
end;
$function$
;

CREATE OR REPLACE FUNCTION public.sync_pending_pin_locations()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  if (tg_op = 'INSERT') or (tg_op = 'UPDATE') then
    if new.status = 'pending' then
      insert into public.pending_pin_locations (pin_id, lat, lng, submitted_at)
      values (new.id, new.lat, new.lng, coalesce(new.submitted_at, now()))
      on conflict (pin_id) do update
        set lat = excluded.lat,
            lng = excluded.lng,
            submitted_at = excluded.submitted_at;
    else
      delete from public.pending_pin_locations where pin_id = new.id;
    end if;
    return new;
  elsif tg_op = 'DELETE' then
    delete from public.pending_pin_locations where pin_id = old.id;
    return old;
  end if;
  return null;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.turnstile_verified()
 RETURNS boolean
 LANGUAGE sql
 STABLE
AS $function$
  select coalesce((auth.jwt()->>'turnstile_passed')::boolean, false);
$function$
;

grant delete on table "public"."bubble_options" to "anon";

grant insert on table "public"."bubble_options" to "anon";

grant references on table "public"."bubble_options" to "anon";

grant select on table "public"."bubble_options" to "anon";

grant trigger on table "public"."bubble_options" to "anon";

grant truncate on table "public"."bubble_options" to "anon";

grant update on table "public"."bubble_options" to "anon";

grant delete on table "public"."bubble_options" to "authenticated";

grant insert on table "public"."bubble_options" to "authenticated";

grant references on table "public"."bubble_options" to "authenticated";

grant select on table "public"."bubble_options" to "authenticated";

grant trigger on table "public"."bubble_options" to "authenticated";

grant truncate on table "public"."bubble_options" to "authenticated";

grant update on table "public"."bubble_options" to "authenticated";

grant delete on table "public"."bubble_options" to "service_role";

grant insert on table "public"."bubble_options" to "service_role";

grant references on table "public"."bubble_options" to "service_role";

grant select on table "public"."bubble_options" to "service_role";

grant trigger on table "public"."bubble_options" to "service_role";

grant truncate on table "public"."bubble_options" to "service_role";

grant update on table "public"."bubble_options" to "service_role";

grant delete on table "public"."messages" to "anon";

grant insert on table "public"."messages" to "anon";

grant references on table "public"."messages" to "anon";

grant select on table "public"."messages" to "anon";

grant trigger on table "public"."messages" to "anon";

grant truncate on table "public"."messages" to "anon";

grant update on table "public"."messages" to "anon";

grant delete on table "public"."messages" to "authenticated";

grant insert on table "public"."messages" to "authenticated";

grant references on table "public"."messages" to "authenticated";

grant select on table "public"."messages" to "authenticated";

grant trigger on table "public"."messages" to "authenticated";

grant truncate on table "public"."messages" to "authenticated";

grant update on table "public"."messages" to "authenticated";

grant delete on table "public"."messages" to "service_role";

grant insert on table "public"."messages" to "service_role";

grant references on table "public"."messages" to "service_role";

grant select on table "public"."messages" to "service_role";

grant trigger on table "public"."messages" to "service_role";

grant truncate on table "public"."messages" to "service_role";

grant update on table "public"."messages" to "service_role";

grant delete on table "public"."moderators" to "anon";

grant insert on table "public"."moderators" to "anon";

grant references on table "public"."moderators" to "anon";

grant select on table "public"."moderators" to "anon";

grant trigger on table "public"."moderators" to "anon";

grant truncate on table "public"."moderators" to "anon";

grant update on table "public"."moderators" to "anon";

grant delete on table "public"."moderators" to "authenticated";

grant insert on table "public"."moderators" to "authenticated";

grant references on table "public"."moderators" to "authenticated";

grant select on table "public"."moderators" to "authenticated";

grant trigger on table "public"."moderators" to "authenticated";

grant truncate on table "public"."moderators" to "authenticated";

grant update on table "public"."moderators" to "authenticated";

grant delete on table "public"."moderators" to "service_role";

grant insert on table "public"."moderators" to "service_role";

grant references on table "public"."moderators" to "service_role";

grant select on table "public"."moderators" to "service_role";

grant trigger on table "public"."moderators" to "service_role";

grant truncate on table "public"."moderators" to "service_role";

grant update on table "public"."moderators" to "service_role";

grant delete on table "public"."pending_pin_locations" to "anon";

grant insert on table "public"."pending_pin_locations" to "anon";

grant references on table "public"."pending_pin_locations" to "anon";

grant select on table "public"."pending_pin_locations" to "anon";

grant trigger on table "public"."pending_pin_locations" to "anon";

grant truncate on table "public"."pending_pin_locations" to "anon";

grant update on table "public"."pending_pin_locations" to "anon";

grant delete on table "public"."pending_pin_locations" to "authenticated";

grant insert on table "public"."pending_pin_locations" to "authenticated";

grant references on table "public"."pending_pin_locations" to "authenticated";

grant select on table "public"."pending_pin_locations" to "authenticated";

grant trigger on table "public"."pending_pin_locations" to "authenticated";

grant truncate on table "public"."pending_pin_locations" to "authenticated";

grant update on table "public"."pending_pin_locations" to "authenticated";

grant delete on table "public"."pending_pin_locations" to "service_role";

grant insert on table "public"."pending_pin_locations" to "service_role";

grant references on table "public"."pending_pin_locations" to "service_role";

grant select on table "public"."pending_pin_locations" to "service_role";

grant trigger on table "public"."pending_pin_locations" to "service_role";

grant truncate on table "public"."pending_pin_locations" to "service_role";

grant update on table "public"."pending_pin_locations" to "service_role";

grant delete on table "public"."pins" to "anon";

grant insert on table "public"."pins" to "anon";

grant references on table "public"."pins" to "anon";

grant select on table "public"."pins" to "anon";

grant trigger on table "public"."pins" to "anon";

grant truncate on table "public"."pins" to "anon";

grant update on table "public"."pins" to "anon";

grant delete on table "public"."pins" to "authenticated";

grant insert on table "public"."pins" to "authenticated";

grant references on table "public"."pins" to "authenticated";

grant select on table "public"."pins" to "authenticated";

grant trigger on table "public"."pins" to "authenticated";

grant truncate on table "public"."pins" to "authenticated";

grant update on table "public"."pins" to "authenticated";

grant delete on table "public"."pins" to "service_role";

grant insert on table "public"."pins" to "service_role";

grant references on table "public"."pins" to "service_role";

grant select on table "public"."pins" to "service_role";

grant trigger on table "public"."pins" to "service_role";

grant truncate on table "public"."pins" to "service_role";

grant update on table "public"."pins" to "service_role";

grant delete on table "public"."turnstile_rate_limits" to "anon";

grant insert on table "public"."turnstile_rate_limits" to "anon";

grant references on table "public"."turnstile_rate_limits" to "anon";

grant select on table "public"."turnstile_rate_limits" to "anon";

grant trigger on table "public"."turnstile_rate_limits" to "anon";

grant truncate on table "public"."turnstile_rate_limits" to "anon";

grant update on table "public"."turnstile_rate_limits" to "anon";

grant delete on table "public"."turnstile_rate_limits" to "authenticated";

grant insert on table "public"."turnstile_rate_limits" to "authenticated";

grant references on table "public"."turnstile_rate_limits" to "authenticated";

grant select on table "public"."turnstile_rate_limits" to "authenticated";

grant trigger on table "public"."turnstile_rate_limits" to "authenticated";

grant truncate on table "public"."turnstile_rate_limits" to "authenticated";

grant update on table "public"."turnstile_rate_limits" to "authenticated";

grant delete on table "public"."turnstile_rate_limits" to "service_role";

grant insert on table "public"."turnstile_rate_limits" to "service_role";

grant references on table "public"."turnstile_rate_limits" to "service_role";

grant select on table "public"."turnstile_rate_limits" to "service_role";

grant trigger on table "public"."turnstile_rate_limits" to "service_role";

grant truncate on table "public"."turnstile_rate_limits" to "service_role";

grant update on table "public"."turnstile_rate_limits" to "service_role";

grant delete on table "public"."turnstile_sessions" to "anon";

grant insert on table "public"."turnstile_sessions" to "anon";

grant references on table "public"."turnstile_sessions" to "anon";

grant select on table "public"."turnstile_sessions" to "anon";

grant trigger on table "public"."turnstile_sessions" to "anon";

grant truncate on table "public"."turnstile_sessions" to "anon";

grant update on table "public"."turnstile_sessions" to "anon";

grant delete on table "public"."turnstile_sessions" to "authenticated";

grant insert on table "public"."turnstile_sessions" to "authenticated";

grant references on table "public"."turnstile_sessions" to "authenticated";

grant select on table "public"."turnstile_sessions" to "authenticated";

grant trigger on table "public"."turnstile_sessions" to "authenticated";

grant truncate on table "public"."turnstile_sessions" to "authenticated";

grant update on table "public"."turnstile_sessions" to "authenticated";

grant delete on table "public"."turnstile_sessions" to "service_role";

grant insert on table "public"."turnstile_sessions" to "service_role";

grant references on table "public"."turnstile_sessions" to "service_role";

grant select on table "public"."turnstile_sessions" to "service_role";

grant trigger on table "public"."turnstile_sessions" to "service_role";

grant truncate on table "public"."turnstile_sessions" to "service_role";

grant update on table "public"."turnstile_sessions" to "service_role";


  create policy "Authenticated moderators can manage bubble options"
  on "public"."bubble_options"
  as permissive
  for all
  to authenticated
using (public.is_moderator(auth.uid()))
with check (public.is_moderator(auth.uid()));



  create policy "Turnstile clients add bubble options"
  on "public"."bubble_options"
  as permissive
  for insert
  to authenticated
with check ((public.turnstile_verified() AND (status = 'pending'::text)));



  create policy "Turnstile clients edit their pending bubbles"
  on "public"."bubble_options"
  as permissive
  for update
  to authenticated
using ((public.turnstile_verified() AND (status = 'pending'::text) AND public.is_request_owner(created_by)))
with check ((public.turnstile_verified() AND (status = 'pending'::text) AND public.is_request_owner(created_by)));



  create policy "Turnstile clients read bubble options"
  on "public"."bubble_options"
  as permissive
  for select
  to authenticated
using ((public.turnstile_verified() AND ((status = 'approved'::text) OR public.is_request_owner(created_by))));



  create policy "Authenticated moderators can manage messages"
  on "public"."messages"
  as permissive
  for all
  to authenticated
using (public.is_moderator(auth.uid()))
with check (public.is_moderator(auth.uid()));



  create policy "Turnstile clients can submit messages"
  on "public"."messages"
  as permissive
  for insert
  to authenticated
with check ((public.turnstile_verified() AND (status = 'open'::text) AND (kind = ANY (ARRAY['site_feedback'::text, 'pin_report'::text]))));



  create policy "Allow trigger to delete locations"
  on "public"."pending_pin_locations"
  as permissive
  for delete
  to public
using (true);



  create policy "Allow trigger to insert locations"
  on "public"."pending_pin_locations"
  as permissive
  for insert
  to public
with check (true);



  create policy "Allow trigger to update locations"
  on "public"."pending_pin_locations"
  as permissive
  for update
  to public
using (true)
with check (true);



  create policy "Enable read access for all users"
  on "public"."pending_pin_locations"
  as permissive
  for select
  to public
using (true);



  create policy "Authenticated moderators can manage pins"
  on "public"."pins"
  as permissive
  for all
  to authenticated
using (public.is_moderator(auth.uid()))
with check (public.is_moderator(auth.uid()));



  create policy "Turnstile clients read approved pins"
  on "public"."pins"
  as permissive
  for select
  to public
using ((public.turnstile_verified() AND (status = 'approved'::text)));



  create policy "Turnstile clients submit pending pins"
  on "public"."pins"
  as permissive
  for insert
  to public
with check ((public.turnstile_verified() AND (status = 'pending'::text) AND (approved = false)));


CREATE TRIGGER pins_pending_delete AFTER DELETE ON public.pins FOR EACH ROW EXECUTE FUNCTION public.sync_pending_pin_locations();

CREATE TRIGGER pins_pending_sync AFTER INSERT OR UPDATE OF status, lat, lng ON public.pins FOR EACH ROW EXECUTE FUNCTION public.sync_pending_pin_locations();


